import type { QueryFunctionContext } from '@tanstack/react-query';
// import { client } from '@/integrations/axios';
import type { Customer } from '@/features/customers/lib/types';

// Deterministic avatar photo via pravatar (seeded by email).
const avatar = (email: string) => `https://i.pravatar.cc/128?u=${encodeURIComponent(email)}`;

// TODO: Replace mock data with real API calls
const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'c-001',
    name: 'Sarah Chen',
    email: 'sarah.chen@northwind.io',
    avatarFallback: 'SC',
    avatarUrl: avatar('sarah.chen@northwind.io'),
    company: 'Northwind Labs',
    plan: 'Enterprise',
    status: 'Active',
    mrr: 4200,
    joinedAt: '2023-08-14',
  },
  {
    id: 'c-002',
    name: 'Marcus Johnson',
    email: 'marcus@helix.dev',
    avatarFallback: 'MJ',
    avatarUrl: avatar('marcus@helix.dev'),
    company: 'Helix Studio',
    plan: 'Pro',
    status: 'Active',
    mrr: 890,
    joinedAt: '2024-01-22',
  },
  {
    id: 'c-003',
    name: 'Elena Petrova',
    email: 'elena.p@aurora.co',
    avatarFallback: 'EP',
    avatarUrl: avatar('elena.p@aurora.co'),
    company: 'Aurora Systems',
    plan: 'Pro',
    status: 'Trial',
    mrr: 0,
    joinedAt: '2026-03-30',
  },
  {
    id: 'c-004',
    name: 'David Kim',
    email: 'dkim@quartz.com',
    avatarFallback: 'DK',
    avatarUrl: avatar('dkim@quartz.com'),
    company: 'Quartz Analytics',
    plan: 'Starter',
    status: 'Active',
    mrr: 240,
    joinedAt: '2024-05-09',
  },
  {
    id: 'c-005',
    name: 'Sophia Diaz',
    email: 'sophia@meridian.app',
    avatarFallback: 'SD',
    avatarUrl: avatar('sophia@meridian.app'),
    company: 'Meridian',
    plan: 'Enterprise',
    status: 'Past Due',
    mrr: 6100,
    joinedAt: '2022-11-03',
  },
  {
    id: 'c-006',
    name: 'James O\u2019Brien',
    email: 'jobrien@plume.studio',
    avatarFallback: 'JO',
    avatarUrl: avatar('jobrien@plume.studio'),
    company: 'Plume Studio',
    plan: 'Pro',
    status: 'Active',
    mrr: 1240,
    joinedAt: '2023-04-17',
  },
  {
    id: 'c-007',
    name: 'Aisha Nair',
    email: 'aisha@brevity.ai',
    avatarFallback: 'AN',
    avatarUrl: avatar('aisha@brevity.ai'),
    company: 'Brevity AI',
    plan: 'Starter',
    status: 'Active',
    mrr: 180,
    joinedAt: '2024-09-12',
  },
  {
    id: 'c-008',
    name: 'Lukas Berg',
    email: 'lukas@verge.io',
    avatarFallback: 'LB',
    avatarUrl: avatar('lukas@verge.io'),
    company: 'Verge',
    plan: 'Free',
    status: 'Trial',
    mrr: 0,
    joinedAt: '2026-04-01',
  },
  {
    id: 'c-009',
    name: 'Mei Tanaka',
    email: 'm.tanaka@kasai.jp',
    avatarFallback: 'MT',
    avatarUrl: avatar('m.tanaka@kasai.jp'),
    company: 'Kasai Group',
    plan: 'Enterprise',
    status: 'Active',
    mrr: 5400,
    joinedAt: '2022-06-21',
  },
  {
    id: 'c-010',
    name: 'Ben Carter',
    email: 'ben@halftide.com',
    avatarFallback: 'BC',
    avatarUrl: avatar('ben@halftide.com'),
    company: 'Halftide',
    plan: 'Pro',
    status: 'Canceled',
    mrr: 0,
    joinedAt: '2023-02-08',
  },
  {
    id: 'c-011',
    name: 'Ines Moreau',
    email: 'ines@octave.fm',
    avatarFallback: 'IM',
    avatarUrl: avatar('ines@octave.fm'),
    company: 'Octave',
    plan: 'Starter',
    status: 'Active',
    mrr: 320,
    joinedAt: '2024-07-25',
  },
  {
    id: 'c-012',
    name: 'Noah Reed',
    email: 'noah.r@sundown.app',
    avatarFallback: 'NR',
    avatarUrl: avatar('noah.r@sundown.app'),
    company: 'Sundown',
    plan: 'Pro',
    status: 'Active',
    mrr: 760,
    joinedAt: '2024-11-14',
  },
  {
    id: 'c-013',
    name: 'Priya Anand',
    email: 'priya@kavach.security',
    avatarFallback: 'PA',
    avatarUrl: avatar('priya@kavach.security'),
    company: 'Kavach',
    plan: 'Enterprise',
    status: 'Active',
    mrr: 7800,
    joinedAt: '2021-12-05',
  },
  {
    id: 'c-014',
    name: 'Tom Becker',
    email: 'tom@finchpath.com',
    avatarFallback: 'TB',
    avatarUrl: avatar('tom@finchpath.com'),
    company: 'Finchpath',
    plan: 'Pro',
    status: 'Trial',
    mrr: 0,
    joinedAt: '2026-04-08',
  },
  {
    id: 'c-015',
    name: 'Hana Park',
    email: 'hana@northbeam.kr',
    avatarFallback: 'HP',
    avatarUrl: avatar('hana@northbeam.kr'),
    company: 'Northbeam',
    plan: 'Starter',
    status: 'Past Due',
    mrr: 240,
    joinedAt: '2024-02-19',
  },
  {
    id: 'c-016',
    name: 'Julian Costa',
    email: 'julian@drift.studio',
    avatarFallback: 'JC',
    avatarUrl: avatar('julian@drift.studio'),
    company: 'Drift',
    plan: 'Pro',
    status: 'Active',
    mrr: 990,
    joinedAt: '2023-10-01',
  },
  {
    id: 'c-017',
    name: 'Olga Volkov',
    email: 'olga@hearth.work',
    avatarFallback: 'OV',
    avatarUrl: avatar('olga@hearth.work'),
    company: 'Hearth',
    plan: 'Enterprise',
    status: 'Active',
    mrr: 4900,
    joinedAt: '2023-03-29',
  },
  {
    id: 'c-018',
    name: 'Ethan Wright',
    email: 'ethan@blip.tv',
    avatarFallback: 'EW',
    avatarUrl: avatar('ethan@blip.tv'),
    company: 'Blip Network',
    plan: 'Free',
    status: 'Canceled',
    mrr: 0,
    joinedAt: '2024-08-04',
  },
  {
    id: 'c-019',
    name: 'Camila Rojas',
    email: 'camila@solstice.mx',
    avatarFallback: 'CR',
    avatarUrl: avatar('camila@solstice.mx'),
    company: 'Solstice',
    plan: 'Pro',
    status: 'Active',
    mrr: 1100,
    joinedAt: '2023-07-16',
  },
  {
    id: 'c-020',
    name: 'Wei Zhang',
    email: 'wei@ledger.fi',
    avatarFallback: 'WZ',
    avatarUrl: avatar('wei@ledger.fi'),
    company: 'Ledger Finance',
    plan: 'Enterprise',
    status: 'Active',
    mrr: 8200,
    joinedAt: '2022-04-11',
  },
  {
    id: 'c-021',
    name: 'Maya Singh',
    email: 'maya@thread.studio',
    avatarFallback: 'MS',
    avatarUrl: avatar('maya@thread.studio'),
    company: 'Thread',
    plan: 'Starter',
    status: 'Trial',
    mrr: 0,
    joinedAt: '2026-04-12',
  },
  {
    id: 'c-022',
    name: 'Diego Martin',
    email: 'diego@fjord.co',
    avatarFallback: 'DM',
    avatarUrl: avatar('diego@fjord.co'),
    company: 'Fjord',
    plan: 'Pro',
    status: 'Active',
    mrr: 720,
    joinedAt: '2024-04-23',
  },
  {
    id: 'c-023',
    name: 'Yusuf Demir',
    email: 'yusuf@cumulus.cloud',
    avatarFallback: 'YD',
    avatarUrl: avatar('yusuf@cumulus.cloud'),
    company: 'Cumulus',
    plan: 'Enterprise',
    status: 'Active',
    mrr: 3600,
    joinedAt: '2023-09-08',
  },
  {
    id: 'c-024',
    name: 'Zoe Williams',
    email: 'zoe@archive.fm',
    avatarFallback: 'ZW',
    avatarUrl: avatar('zoe@archive.fm'),
    company: 'Archive FM',
    plan: 'Pro',
    status: 'Active',
    mrr: 880,
    joinedAt: '2024-06-30',
  },
  {
    id: 'c-025',
    name: 'Rafael Costa',
    email: 'rafael@embers.gg',
    avatarFallback: 'RC',
    avatarUrl: avatar('rafael@embers.gg'),
    company: 'Embers',
    plan: 'Free',
    status: 'Trial',
    mrr: 0,
    joinedAt: '2026-04-05',
  },
  {
    id: 'c-026',
    name: 'Linnea Holm',
    email: 'linnea@nordlys.no',
    avatarFallback: 'LH',
    avatarUrl: avatar('linnea@nordlys.no'),
    company: 'Nordlys',
    plan: 'Starter',
    status: 'Active',
    mrr: 290,
    joinedAt: '2024-10-19',
  },
  {
    id: 'c-027',
    name: 'Theo Laurent',
    email: 'theo@parallax.dev',
    avatarFallback: 'TL',
    avatarUrl: avatar('theo@parallax.dev'),
    company: 'Parallax',
    plan: 'Pro',
    status: 'Past Due',
    mrr: 1240,
    joinedAt: '2023-05-27',
  },
  {
    id: 'c-028',
    name: 'Naomi Green',
    email: 'naomi@bramble.shop',
    avatarFallback: 'NG',
    avatarUrl: avatar('naomi@bramble.shop'),
    company: 'Bramble',
    plan: 'Pro',
    status: 'Active',
    mrr: 950,
    joinedAt: '2024-12-02',
  },
  {
    id: 'c-029',
    name: 'Pavel Novak',
    email: 'pavel@axiom.cz',
    avatarFallback: 'PN',
    avatarUrl: avatar('pavel@axiom.cz'),
    company: 'Axiom',
    plan: 'Enterprise',
    status: 'Canceled',
    mrr: 0,
    joinedAt: '2022-08-15',
  },
  {
    id: 'c-030',
    name: 'Ivy Sato',
    email: 'ivy@harbor.studio',
    avatarFallback: 'IS',
    avatarUrl: avatar('ivy@harbor.studio'),
    company: 'Harbor',
    plan: 'Starter',
    status: 'Active',
    mrr: 200,
    joinedAt: '2025-01-10',
  },
];

// biome-ignore lint/correctness/noUnusedFunctionParameters: Only used for demonstration purposes, but required by TanStack Query's API
export async function getCustomers({ signal }: QueryFunctionContext): Promise<Customer[]> {
  // Real implementation - axios reads `signal` natively and aborts the HTTP request when TanStack Query cancels (navigation, unmount, refetch):
  //   const res = await client.get<Customer[]>('/customers', { signal });
  //   return res.data;
  return MOCK_CUSTOMERS;
}

// biome-ignore lint/correctness/noUnusedFunctionParameters: Only used for demonstration purposes, but required by TanStack Query's API
export async function getCustomer(id: string, { signal }: QueryFunctionContext): Promise<Customer> {
  // Real implementation:
  //   const res = await client.get<Customer>(`/customers/${id}`, { signal });
  //   return res.data;
  const customer = MOCK_CUSTOMERS.find((c) => c.id === id);
  if (!customer) throw new Error(`Customer ${id} not found`);
  return customer;
}
