import type { QueryFunctionContext } from '@tanstack/react-query';
// import { client } from '@/integrations/axios';
import type { User } from '@/features/users/lib/types';

// Deterministic avatar photo via pravatar (seeded by email).
const avatar = (email: string) => `https://i.pravatar.cc/128?u=${encodeURIComponent(email)}`;

// TODO: Replace mock data with real API calls
const MOCK_USERS: User[] = [
  {
    id: 1,
    name: 'Ada Lovelace',
    email: 'ada@soldevelo.com',
    username: 'ada',
    avatarFallback: 'AL',
    avatarUrl: avatar('ada@soldevelo.com'),
    role: 'Owner',
    status: 'Active',
    lastActiveAt: '2026-04-20T08:14:00Z',
    joinedAt: '2021-03-02',
  },
  {
    id: 2,
    name: 'Grace Hopper',
    email: 'grace@soldevelo.com',
    username: 'grace',
    avatarFallback: 'GH',
    avatarUrl: avatar('grace@soldevelo.com'),
    role: 'Admin',
    status: 'Active',
    lastActiveAt: '2026-04-20T07:02:00Z',
    joinedAt: '2021-05-18',
  },
  {
    id: 3,
    name: 'Alan Turing',
    email: 'alan@soldevelo.com',
    username: 'alan',
    avatarFallback: 'AT',
    avatarUrl: avatar('alan@soldevelo.com'),
    role: 'Admin',
    status: 'Active',
    lastActiveAt: '2026-04-19T21:40:00Z',
    joinedAt: '2021-06-30',
  },
  {
    id: 4,
    name: 'Katherine Johnson',
    email: 'kat@soldevelo.com',
    username: 'kat',
    avatarFallback: 'KJ',
    avatarUrl: avatar('kat@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-19T14:12:00Z',
    joinedAt: '2022-01-11',
  },
  {
    id: 5,
    name: 'Linus Torvalds',
    email: 'linus@soldevelo.com',
    username: 'linus',
    avatarFallback: 'LT',
    avatarUrl: avatar('linus@soldevelo.com'),
    role: 'Admin',
    status: 'Active',
    lastActiveAt: '2026-04-20T06:48:00Z',
    joinedAt: '2022-02-20',
  },
  {
    id: 6,
    name: 'Hedy Lamarr',
    email: 'hedy@soldevelo.com',
    username: 'hedy',
    avatarFallback: 'HL',
    avatarUrl: avatar('hedy@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-18T09:03:00Z',
    joinedAt: '2022-04-05',
  },
  {
    id: 7,
    name: 'Donald Knuth',
    email: 'knuth@soldevelo.com',
    username: 'knuth',
    avatarFallback: 'DK',
    avatarUrl: avatar('knuth@soldevelo.com'),
    role: 'Viewer',
    status: 'Active',
    lastActiveAt: '2026-04-15T16:20:00Z',
    joinedAt: '2022-06-14',
  },
  {
    id: 8,
    name: 'Margaret Hamilton',
    email: 'margaret@soldevelo.com',
    username: 'margaret',
    avatarFallback: 'MH',
    avatarUrl: avatar('margaret@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-20T05:55:00Z',
    joinedAt: '2022-08-22',
  },
  {
    id: 9,
    name: 'Ken Thompson',
    email: 'ken@soldevelo.com',
    username: 'ken',
    avatarFallback: 'KT',
    avatarUrl: avatar('ken@soldevelo.com'),
    role: 'Member',
    status: 'Suspended',
    lastActiveAt: '2026-03-28T11:10:00Z',
    joinedAt: '2022-09-30',
  },
  {
    id: 10,
    name: 'Barbara Liskov',
    email: 'barbara@soldevelo.com',
    username: 'barbara',
    avatarFallback: 'BL',
    avatarUrl: avatar('barbara@soldevelo.com'),
    role: 'Admin',
    status: 'Active',
    lastActiveAt: '2026-04-20T04:22:00Z',
    joinedAt: '2022-11-07',
  },
  {
    id: 11,
    name: 'Tim Berners-Lee',
    email: 'tim@soldevelo.com',
    username: 'timbl',
    avatarFallback: 'TB',
    avatarUrl: avatar('tim@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-19T19:05:00Z',
    joinedAt: '2023-01-15',
  },
  {
    id: 12,
    name: 'Radia Perlman',
    email: 'radia@soldevelo.com',
    username: 'radia',
    avatarFallback: 'RP',
    avatarUrl: avatar('radia@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-20T03:10:00Z',
    joinedAt: '2023-02-28',
  },
  {
    id: 13,
    name: 'Anita Borg',
    email: 'anita@soldevelo.com',
    username: 'anita',
    avatarFallback: 'AB',
    avatarUrl: avatar('anita@soldevelo.com'),
    role: 'Viewer',
    status: 'Active',
    lastActiveAt: '2026-04-17T10:30:00Z',
    joinedAt: '2023-04-12',
  },
  {
    id: 14,
    name: 'Brian Kernighan',
    email: 'brian@soldevelo.com',
    username: 'brian',
    avatarFallback: 'BK',
    avatarUrl: avatar('brian@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-20T07:50:00Z',
    joinedAt: '2023-06-03',
  },
  {
    id: 15,
    name: 'Frances Allen',
    email: 'frances@soldevelo.com',
    username: 'frances',
    avatarFallback: 'FA',
    avatarUrl: avatar('frances@soldevelo.com'),
    role: 'Member',
    status: 'Invited',
    lastActiveAt: '2026-04-18T15:44:00Z',
    joinedAt: '2026-04-18',
  },
  {
    id: 16,
    name: 'Guido van Rossum',
    email: 'guido@soldevelo.com',
    username: 'guido',
    avatarFallback: 'GR',
    avatarUrl: avatar('guido@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-20T02:28:00Z',
    joinedAt: '2023-07-21',
  },
  {
    id: 17,
    name: 'Sophie Wilson',
    email: 'sophie@soldevelo.com',
    username: 'sophie',
    avatarFallback: 'SW',
    avatarUrl: avatar('sophie@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-16T12:15:00Z',
    joinedAt: '2023-09-08',
  },
  {
    id: 18,
    name: 'James Gosling',
    email: 'james@soldevelo.com',
    username: 'james',
    avatarFallback: 'JG',
    avatarUrl: avatar('james@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-19T22:01:00Z',
    joinedAt: '2023-11-14',
  },
  {
    id: 19,
    name: 'Adele Goldberg',
    email: 'adele@soldevelo.com',
    username: 'adele',
    avatarFallback: 'AG',
    avatarUrl: avatar('adele@soldevelo.com'),
    role: 'Viewer',
    status: 'Active',
    lastActiveAt: '2026-04-10T09:00:00Z',
    joinedAt: '2024-01-23',
  },
  {
    id: 20,
    name: 'Vint Cerf',
    email: 'vint@soldevelo.com',
    username: 'vint',
    avatarFallback: 'VC',
    avatarUrl: avatar('vint@soldevelo.com'),
    role: 'Member',
    status: 'Invited',
    lastActiveAt: '2026-04-19T11:27:00Z',
    joinedAt: '2026-04-19',
  },
  {
    id: 21,
    name: 'Dennis Ritchie',
    email: 'dennis@soldevelo.com',
    username: 'dennis',
    avatarFallback: 'DR',
    avatarUrl: avatar('dennis@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-20T01:11:00Z',
    joinedAt: '2024-03-07',
  },
  {
    id: 22,
    name: 'Shafi Goldwasser',
    email: 'shafi@soldevelo.com',
    username: 'shafi',
    avatarFallback: 'SG',
    avatarUrl: avatar('shafi@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-14T17:40:00Z',
    joinedAt: '2024-05-19',
  },
  {
    id: 23,
    name: 'Edsger Dijkstra',
    email: 'edsger@soldevelo.com',
    username: 'edsger',
    avatarFallback: 'ED',
    avatarUrl: avatar('edsger@soldevelo.com'),
    role: 'Viewer',
    status: 'Suspended',
    lastActiveAt: '2026-02-11T08:22:00Z',
    joinedAt: '2024-07-04',
  },
  {
    id: 24,
    name: 'Carol Shaw',
    email: 'carol@soldevelo.com',
    username: 'carol',
    avatarFallback: 'CS',
    avatarUrl: avatar('carol@soldevelo.com'),
    role: 'Member',
    status: 'Invited',
    lastActiveAt: '2026-04-20T09:00:00Z',
    joinedAt: '2026-04-20',
  },
  {
    id: 25,
    name: 'Rob Pike',
    email: 'rob@soldevelo.com',
    username: 'rob',
    avatarFallback: 'RP',
    avatarUrl: avatar('rob@soldevelo.com'),
    role: 'Member',
    status: 'Active',
    lastActiveAt: '2026-04-20T06:06:00Z',
    joinedAt: '2024-10-02',
  },
];

// biome-ignore lint/correctness/noUnusedFunctionParameters: Only used for demonstration purposes, but required by TanStack Query's API
export async function getUsers({ signal }: QueryFunctionContext): Promise<User[]> {
  // Real implementation - axios reads `signal` natively and aborts the HTTP request when TanStack Query cancels (navigation, unmount, refetch):
  //   const res = await client.get<User[]>('/users', { signal });
  //   return res.data;
  return MOCK_USERS;
}

// biome-ignore lint/correctness/noUnusedFunctionParameters: Only used for demonstration purposes, but required by TanStack Query's API
export async function getUser(id: string, { signal }: QueryFunctionContext): Promise<User> {
  // Real implementation:
  //   const res = await client.get<User>(`/users/${id}`, { signal });
  //   return res.data;
  const user = MOCK_USERS.find((u) => u.id === Number(id));
  if (!user) throw new Error(`User ${id} not found`);
  return user;
}
