/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedProtectedRouteImport } from './routes/(protected)/_protected'
import { Route as protectedProtectedCustomersRouteImport } from './routes/(protected)/_protected.customers'
import { Route as protectedProtectedDashboardRouteImport } from './routes/(protected)/_protected.dashboard'
import { Route as protectedProtectedNewProjectRouteImport } from './routes/(protected)/_protected.new-project'
import { Route as protectedProtectedStockMovementRouteImport } from './routes/(protected)/_protected.stock-movement'
import { Route as protectedProtectedUsersRouteImport } from './routes/(protected)/_protected.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProtectedRoute = protectedProtectedRouteImport.update({
  id: '/(protected)/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProtectedCustomersRoute =
  protectedProtectedCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => protectedProtectedRoute,
  } as any)
const protectedProtectedDashboardRoute =
  protectedProtectedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => protectedProtectedRoute,
  } as any)
const protectedProtectedNewProjectRoute =
  protectedProtectedNewProjectRouteImport.update({
    id: '/new-project',
    path: '/new-project',
    getParentRoute: () => protectedProtectedRoute,
  } as any)
const protectedProtectedStockMovementRoute =
  protectedProtectedStockMovementRouteImport.update({
    id: '/stock-movement',
    path: '/stock-movement',
    getParentRoute: () => protectedProtectedRoute,
  } as any)
const protectedProtectedUsersRoute = protectedProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => protectedProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof protectedProtectedCustomersRoute
  '/dashboard': typeof protectedProtectedDashboardRoute
  '/new-project': typeof protectedProtectedNewProjectRoute
  '/stock-movement': typeof protectedProtectedStockMovementRoute
  '/users': typeof protectedProtectedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof protectedProtectedCustomersRoute
  '/dashboard': typeof protectedProtectedDashboardRoute
  '/new-project': typeof protectedProtectedNewProjectRoute
  '/stock-movement': typeof protectedProtectedStockMovementRoute
  '/users': typeof protectedProtectedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(protected)/_protected': typeof protectedProtectedRouteWithChildren
  '/(protected)/_protected/customers': typeof protectedProtectedCustomersRoute
  '/(protected)/_protected/dashboard': typeof protectedProtectedDashboardRoute
  '/(protected)/_protected/new-project': typeof protectedProtectedNewProjectRoute
  '/(protected)/_protected/stock-movement': typeof protectedProtectedStockMovementRoute
  '/(protected)/_protected/users': typeof protectedProtectedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/new-project'
    | '/stock-movement'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/new-project'
    | '/stock-movement'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(protected)/_protected'
    | '/(protected)/_protected/customers'
    | '/(protected)/_protected/dashboard'
    | '/(protected)/_protected/new-project'
    | '/(protected)/_protected/stock-movement'
    | '/(protected)/_protected/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  protectedProtectedRoute: typeof protectedProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_protected': {
      id: '/(protected)/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_protected/customers': {
      id: '/(protected)/_protected/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof protectedProtectedCustomersRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
    '/(protected)/_protected/dashboard': {
      id: '/(protected)/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedProtectedDashboardRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
    '/(protected)/_protected/new-project': {
      id: '/(protected)/_protected/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof protectedProtectedNewProjectRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
    '/(protected)/_protected/stock-movement': {
      id: '/(protected)/_protected/stock-movement'
      path: '/stock-movement'
      fullPath: '/stock-movement'
      preLoaderRoute: typeof protectedProtectedStockMovementRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
    '/(protected)/_protected/users': {
      id: '/(protected)/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof protectedProtectedUsersRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
  }
}

interface protectedProtectedRouteChildren {
  protectedProtectedCustomersRoute: typeof protectedProtectedCustomersRoute
  protectedProtectedDashboardRoute: typeof protectedProtectedDashboardRoute
  protectedProtectedNewProjectRoute: typeof protectedProtectedNewProjectRoute
  protectedProtectedStockMovementRoute: typeof protectedProtectedStockMovementRoute
  protectedProtectedUsersRoute: typeof protectedProtectedUsersRoute
}

const protectedProtectedRouteChildren: protectedProtectedRouteChildren = {
  protectedProtectedCustomersRoute: protectedProtectedCustomersRoute,
  protectedProtectedDashboardRoute: protectedProtectedDashboardRoute,
  protectedProtectedNewProjectRoute: protectedProtectedNewProjectRoute,
  protectedProtectedStockMovementRoute: protectedProtectedStockMovementRoute,
  protectedProtectedUsersRoute: protectedProtectedUsersRoute,
}

const protectedProtectedRouteWithChildren =
  protectedProtectedRoute._addFileChildren(protectedProtectedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  protectedProtectedRoute: protectedProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
