/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedProtectedRouteImport } from './routes/(protected)/_protected'
import { Route as protectedProtectedHomeRouteImport } from './routes/(protected)/_protected.home'
import { Route as protectedProtectedProfileRouteImport } from './routes/(protected)/_protected.profile'
import { Route as protectedProtectedAdministrationRolesRouteImport } from './routes/(protected)/_protected.administration.roles'
import { Route as protectedProtectedAdministrationServiceAccountsRouteImport } from './routes/(protected)/_protected.administration.service-accounts'
import { Route as protectedProtectedAdministrationUsersRouteImport } from './routes/(protected)/_protected.administration.users'
import { Route as protectedProtectedProfileIndexRouteImport } from './routes/(protected)/_protected.profile.index'
import { Route as protectedProtectedProfileNotificationsRouteImport } from './routes/(protected)/_protected.profile.notifications'
import { Route as protectedProtectedProfileRolesRouteImport } from './routes/(protected)/_protected.profile.roles'
import { Route as protectedProtectedAdministrationUsersIdRolesRouteImport } from './routes/(protected)/_protected.administration.users_.$id.roles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProtectedRoute = protectedProtectedRouteImport.update({
  id: '/(protected)/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProtectedHomeRoute = protectedProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => protectedProtectedRoute,
} as any)
const protectedProtectedProfileRoute =
  protectedProtectedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => protectedProtectedRoute,
  } as any)
const protectedProtectedAdministrationRolesRoute =
  protectedProtectedAdministrationRolesRouteImport.update({
    id: '/administration/roles',
    path: '/administration/roles',
    getParentRoute: () => protectedProtectedRoute,
  } as any)
const protectedProtectedAdministrationServiceAccountsRoute =
  protectedProtectedAdministrationServiceAccountsRouteImport.update({
    id: '/administration/service-accounts',
    path: '/administration/service-accounts',
    getParentRoute: () => protectedProtectedRoute,
  } as any)
const protectedProtectedAdministrationUsersRoute =
  protectedProtectedAdministrationUsersRouteImport.update({
    id: '/administration/users',
    path: '/administration/users',
    getParentRoute: () => protectedProtectedRoute,
  } as any)
const protectedProtectedProfileIndexRoute =
  protectedProtectedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedProtectedProfileRoute,
  } as any)
const protectedProtectedProfileNotificationsRoute =
  protectedProtectedProfileNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => protectedProtectedProfileRoute,
  } as any)
const protectedProtectedProfileRolesRoute =
  protectedProtectedProfileRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => protectedProtectedProfileRoute,
  } as any)
const protectedProtectedAdministrationUsersIdRolesRoute =
  protectedProtectedAdministrationUsersIdRolesRouteImport.update({
    id: '/administration/users_/$id/roles',
    path: '/administration/users/$id/roles',
    getParentRoute: () => protectedProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof protectedProtectedHomeRoute
  '/profile': typeof protectedProtectedProfileRouteWithChildren
  '/administration/roles': typeof protectedProtectedAdministrationRolesRoute
  '/administration/service-accounts': typeof protectedProtectedAdministrationServiceAccountsRoute
  '/administration/users': typeof protectedProtectedAdministrationUsersRoute
  '/profile/notifications': typeof protectedProtectedProfileNotificationsRoute
  '/profile/roles': typeof protectedProtectedProfileRolesRoute
  '/profile/': typeof protectedProtectedProfileIndexRoute
  '/administration/users/$id/roles': typeof protectedProtectedAdministrationUsersIdRolesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof protectedProtectedHomeRoute
  '/administration/roles': typeof protectedProtectedAdministrationRolesRoute
  '/administration/service-accounts': typeof protectedProtectedAdministrationServiceAccountsRoute
  '/administration/users': typeof protectedProtectedAdministrationUsersRoute
  '/profile/notifications': typeof protectedProtectedProfileNotificationsRoute
  '/profile/roles': typeof protectedProtectedProfileRolesRoute
  '/profile': typeof protectedProtectedProfileIndexRoute
  '/administration/users/$id/roles': typeof protectedProtectedAdministrationUsersIdRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(protected)/_protected': typeof protectedProtectedRouteWithChildren
  '/(protected)/_protected/home': typeof protectedProtectedHomeRoute
  '/(protected)/_protected/profile': typeof protectedProtectedProfileRouteWithChildren
  '/(protected)/_protected/administration/roles': typeof protectedProtectedAdministrationRolesRoute
  '/(protected)/_protected/administration/service-accounts': typeof protectedProtectedAdministrationServiceAccountsRoute
  '/(protected)/_protected/administration/users': typeof protectedProtectedAdministrationUsersRoute
  '/(protected)/_protected/profile/notifications': typeof protectedProtectedProfileNotificationsRoute
  '/(protected)/_protected/profile/roles': typeof protectedProtectedProfileRolesRoute
  '/(protected)/_protected/profile/': typeof protectedProtectedProfileIndexRoute
  '/(protected)/_protected/administration/users_/$id/roles': typeof protectedProtectedAdministrationUsersIdRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/home'
    | '/profile'
    | '/administration/roles'
    | '/administration/service-accounts'
    | '/administration/users'
    | '/profile/notifications'
    | '/profile/roles'
    | '/profile/'
    | '/administration/users/$id/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/home'
    | '/administration/roles'
    | '/administration/service-accounts'
    | '/administration/users'
    | '/profile/notifications'
    | '/profile/roles'
    | '/profile'
    | '/administration/users/$id/roles'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(protected)/_protected'
    | '/(protected)/_protected/home'
    | '/(protected)/_protected/profile'
    | '/(protected)/_protected/administration/roles'
    | '/(protected)/_protected/administration/service-accounts'
    | '/(protected)/_protected/administration/users'
    | '/(protected)/_protected/profile/notifications'
    | '/(protected)/_protected/profile/roles'
    | '/(protected)/_protected/profile/'
    | '/(protected)/_protected/administration/users_/$id/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  protectedProtectedRoute: typeof protectedProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_protected': {
      id: '/(protected)/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_protected/home': {
      id: '/(protected)/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof protectedProtectedHomeRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
    '/(protected)/_protected/profile': {
      id: '/(protected)/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedProtectedProfileRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
    '/(protected)/_protected/administration/roles': {
      id: '/(protected)/_protected/administration/roles'
      path: '/administration/roles'
      fullPath: '/administration/roles'
      preLoaderRoute: typeof protectedProtectedAdministrationRolesRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
    '/(protected)/_protected/administration/service-accounts': {
      id: '/(protected)/_protected/administration/service-accounts'
      path: '/administration/service-accounts'
      fullPath: '/administration/service-accounts'
      preLoaderRoute: typeof protectedProtectedAdministrationServiceAccountsRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
    '/(protected)/_protected/administration/users': {
      id: '/(protected)/_protected/administration/users'
      path: '/administration/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof protectedProtectedAdministrationUsersRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
    '/(protected)/_protected/profile/': {
      id: '/(protected)/_protected/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof protectedProtectedProfileIndexRouteImport
      parentRoute: typeof protectedProtectedProfileRoute
    }
    '/(protected)/_protected/profile/notifications': {
      id: '/(protected)/_protected/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof protectedProtectedProfileNotificationsRouteImport
      parentRoute: typeof protectedProtectedProfileRoute
    }
    '/(protected)/_protected/profile/roles': {
      id: '/(protected)/_protected/profile/roles'
      path: '/roles'
      fullPath: '/profile/roles'
      preLoaderRoute: typeof protectedProtectedProfileRolesRouteImport
      parentRoute: typeof protectedProtectedProfileRoute
    }
    '/(protected)/_protected/administration/users_/$id/roles': {
      id: '/(protected)/_protected/administration/users_/$id/roles'
      path: '/administration/users/$id/roles'
      fullPath: '/administration/users/$id/roles'
      preLoaderRoute: typeof protectedProtectedAdministrationUsersIdRolesRouteImport
      parentRoute: typeof protectedProtectedRoute
    }
  }
}

interface protectedProtectedProfileRouteChildren {
  protectedProtectedProfileNotificationsRoute: typeof protectedProtectedProfileNotificationsRoute
  protectedProtectedProfileRolesRoute: typeof protectedProtectedProfileRolesRoute
  protectedProtectedProfileIndexRoute: typeof protectedProtectedProfileIndexRoute
}

const protectedProtectedProfileRouteChildren: protectedProtectedProfileRouteChildren =
  {
    protectedProtectedProfileNotificationsRoute:
      protectedProtectedProfileNotificationsRoute,
    protectedProtectedProfileRolesRoute: protectedProtectedProfileRolesRoute,
    protectedProtectedProfileIndexRoute: protectedProtectedProfileIndexRoute,
  }

const protectedProtectedProfileRouteWithChildren =
  protectedProtectedProfileRoute._addFileChildren(
    protectedProtectedProfileRouteChildren,
  )

interface protectedProtectedRouteChildren {
  protectedProtectedHomeRoute: typeof protectedProtectedHomeRoute
  protectedProtectedProfileRoute: typeof protectedProtectedProfileRouteWithChildren
  protectedProtectedAdministrationRolesRoute: typeof protectedProtectedAdministrationRolesRoute
  protectedProtectedAdministrationServiceAccountsRoute: typeof protectedProtectedAdministrationServiceAccountsRoute
  protectedProtectedAdministrationUsersRoute: typeof protectedProtectedAdministrationUsersRoute
  protectedProtectedAdministrationUsersIdRolesRoute: typeof protectedProtectedAdministrationUsersIdRolesRoute
}

const protectedProtectedRouteChildren: protectedProtectedRouteChildren = {
  protectedProtectedHomeRoute: protectedProtectedHomeRoute,
  protectedProtectedProfileRoute: protectedProtectedProfileRouteWithChildren,
  protectedProtectedAdministrationRolesRoute:
    protectedProtectedAdministrationRolesRoute,
  protectedProtectedAdministrationServiceAccountsRoute:
    protectedProtectedAdministrationServiceAccountsRoute,
  protectedProtectedAdministrationUsersRoute:
    protectedProtectedAdministrationUsersRoute,
  protectedProtectedAdministrationUsersIdRolesRoute:
    protectedProtectedAdministrationUsersIdRolesRoute,
}

const protectedProtectedRouteWithChildren =
  protectedProtectedRoute._addFileChildren(protectedProtectedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  protectedProtectedRoute: protectedProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
